// <auto-generated />
using System;
using ControleHoras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleHoras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608003643_AddIntervaloMinimoMinutos")]
    partial class AddIntervaloMinimoMinutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ControleHoras.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BancoHorasMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloMinimoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<double>("JornadaDiariaHoras")
                        .HasColumnType("REAL");

                    b.Property<int>("ToleranciaMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("ControleHoras.Models.RegistroPonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EntradaManha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EntradaTarde")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("SaidaManha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("SaidaTarde")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrosPonto");
                });
#pragma warning restore 612, 618
        }
    }
}
